spring:
  output:
    ansi:
      enabled: ALWAYS
application:
  baseName: messages
  defaultLocale: en
  name: staffmanager
  title: Manage cool people
  version: 1.0

server:
  port: 8088
#  error:
#    whitelabel:
#      enabled: false

logging:
  level:
    root: INFO
