spring:
  web:
    resources:
      add-mappings: false
  output:
    ansi:
      enabled: ALWAYS
application:
  baseName: messages
  defaultLocale: en
  name: staffmanager
  title: Manage cool people
  version: 1.0

server:
  port: 8088
  error:
    path: /error
#  error:
#    whitelabel:
#      enabled: false

logging:
  level:
    root: INFO

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health, info